name: uni_helper
description: "A new Flutter project for students."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Основні пакети Firebase
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  
  # Додаткові корисні пакети для нашого ТЗ
  cupertino_icons: ^1.0.6
  google_sign_in: ^6.2.1
  intl: ^0.20.2 # Для форматування дати у розкладі
  url_launcher: ^6.3.2
  table_calendar: ^3.1.2 # Найкращий віджет календаря для Flutter
  flutter_local_notifications: ^18.0.1 # Для нагадувань
  timezone: ^0.10.0 # Для правильної роботи часу сповіщень

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Якщо у вас будуть картинки, розкоментуйте це пізніше:
  # assets:
  #   - assets/images/