name: uni_helper
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.10.8

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # Іконки
  cupertino_icons: ^1.0.8

  # Для роботи з офіційним розкладом університету (HTTP запити)
  http: ^1.1.0

  # Для форматування дат та часу
  intl: ^0.18.1

  # Для реалізації скелетонів (заглушок завантаження) у Soft UI стилі
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Рекомендовані правила лінтингу для чистого коду
  flutter_lints: ^2.0.0

# Специфічні налаштування Flutter
flutter:

  # Включення Material Icons для використання Icons.calendar_month тощо
  uses-material-design: true

  # Якщо ви плануєте використовувати кастомні шрифти або зображення, 
  # розкоментуйте відповідні секції нижче:
  # assets:
  #   - assets/images/
  
  # fonts:
  #   - family: Montserrat
  #     fonts:
  #       - asset: fonts/Montserrat-Regular.ttf
  #       - asset: fonts/Montserrat-Bold.ttf
  #         weight: 700